### ISSUE TITLE
Create First Homework

### ISSUE THREAD

**Issue by AtirathD** [AtirathD/ASTR-119#1]
first hw

**Comment by brucelaughlin** [comment]
Hi there,

I don't see a "first-homework.py" file in your repository; please let me know if you're having any trouble or are struggling with this stuff.  We're here to help - writing code and using Github can be really challenging, so please reach out if you are struggling.

-Bruce

**Comment by AtirathD** [comment]
Hi Bruce,
I just uploaded the file. Could you please double check, and let me know if
you are able to see the file now? Thanks for checking in with me!

Best,
Atirath
